import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Сайдбар строится автоматически по структуре папки docs/.
// Порядок задаётся через sidebar_position во frontmatter
// или через _category_.json внутри папок.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
